spring:
  security:
    oauth2:
      client:
        registration:
          custom-google:
            client-id: 'id'
            client-secret: 'secret'
        provider:
          custom-google:
            issuer-uri: https://accounts.google.com